# Generated by Django 5.0.3 on 2024-05-03 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_top_alter_product_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='top',
            field=models.BooleanField(default=False),
        ),
    ]
