# Generated by Django 5.0.3 on 2024-05-03 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_subcategory_top'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='top',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='top',
        ),
        migrations.AddField(
            model_name='supercategory',
            name='second',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supercategory',
            name='top',
            field=models.BooleanField(default=True),
        ),
    ]
