# Generated by Django 5.0.3 on 2024-05-04 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_category_top_remove_subcategory_top_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categories',
            new_name='category',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='last',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='producttranslation',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
    ]
