# Generated by Django 5.0.3 on 2024-05-04 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_categories_product_category_subcategory_last_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttranslation',
            name='name',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='product_name'),
        ),
    ]
