# Generated by Django 5.0.3 on 2024-05-04 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_producttranslation_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttranslation',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='product_name'),
        ),
        migrations.AlterField(
            model_name='producttranslation',
            name='slug',
            field=models.SlugField(blank=True, max_length=130, unique=True, verbose_name='url'),
        ),
    ]
