# Generated by Django 5.0.3 on 2024-05-04 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_producttranslation_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='last',
        ),
    ]
