# Generated by Django 5.0.3 on 2024-05-05 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_producttype_product_is_prioritized_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_type',
            new_name='type',
        ),
    ]
