# Generated by Django 5.0.3 on 2024-05-05 19:31

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_brand_brandcountry_alter_product_type_product_brand_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charachteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'product_char',
                'verbose_name_plural': 'product_chars',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.AlterField(
            model_name='brandcountrytranslation',
            name='name',
            field=models.CharField(max_length=40, unique=True, verbose_name='country'),
        ),
        migrations.AddField(
            model_name='supercategory',
            name='charachteristic',
            field=models.ManyToManyField(blank=True, to='products.charachteristic'),
        ),
        migrations.CreateModel(
            name='CharachteristicValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charachteristic_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='products.charachteristic', verbose_name='char_name')),
            ],
            options={
                'verbose_name': 'product_char_value',
                'verbose_name_plural': 'product_char_values',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='product',
            name='charachteristics',
            field=models.ManyToManyField(blank=True, to='products.charachteristicvalue'),
        ),
        migrations.CreateModel(
            name='CharachteristicTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='char_name')),
                ('slug', models.SlugField(unique=True, verbose_name='url')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='products.charachteristic')),
            ],
            options={
                'verbose_name': 'product_char Translation',
                'db_table': 'products_charachteristic_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CharachteristicValueTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('value', models.CharField(max_length=40, unique=True, verbose_name='char_value_name')),
                ('slug', models.SlugField(unique=True, verbose_name='url')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='products.charachteristicvalue')),
            ],
            options={
                'verbose_name': 'product_char_value Translation',
                'db_table': 'products_charachteristicvalue_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
