# Generated by Django 5.0.3 on 2024-05-09 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_charachteristic_alter_brandcountrytranslation_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttypetranslation',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='product_type'),
        ),
    ]
