# Generated by Django 5.0.3 on 2024-05-19 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_producttypetranslation_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
        migrations.AlterModelOptions(
            name='producttype',
            options={'verbose_name': 'product_type', 'verbose_name_plural': 'product_types'},
        ),
        migrations.AlterModelOptions(
            name='producttypetranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'product_type Translation'},
        ),
        migrations.AddField(
            model_name='brand',
            name='charachteristic',
            field=models.ManyToManyField(blank=True, to='products.charachteristic'),
        ),
    ]
