# Generated by Django 5.0.3 on 2024-05-12 12:20

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docsectiontranslation',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='doc_section_text'),
        ),
    ]
