# Generated by Django 5.0.3 on 2024-05-15 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slidertranslation',
            old_name='link_text',
            new_name='button_text',
        ),
    ]
