# Generated by Django 5.0.3 on 2024-05-17 13:18

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_rename_link_text_slidertranslation_button_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/links/module/%Y/%m/%d', verbose_name='module_img')),
                ('background', models.ImageField(upload_to='images/links/module/%Y/%m/%d/background', verbose_name='module_background')),
            ],
            options={
                'verbose_name': 'module',
                'verbose_name_plural': 'modules',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PopularTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/links/tab/%Y/%m/%d', verbose_name='tab_img')),
                ('background', models.ImageField(upload_to='images/links/tab/%Y/%m/%d/background', verbose_name='tab_background')),
            ],
            options={
                'verbose_name': 'popular_tab',
                'verbose_name_plural': 'popular_tabs',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'slider', 'verbose_name_plural': 'sliders'},
        ),
        migrations.AlterField(
            model_name='slider',
            name='img',
            field=models.ImageField(upload_to='images/links/slider/%Y/%m/%d', verbose_name='slider_img'),
        ),
        migrations.CreateModel(
            name='ModuleTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='module_title')),
                ('text', models.CharField(max_length=100, verbose_name='module_text')),
                ('button_text', models.CharField(max_length=30, verbose_name='module_link_text')),
                ('link', models.CharField(max_length=128, verbose_name='module_link')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='links.module')),
            ],
            options={
                'verbose_name': 'module Translation',
                'db_table': 'links_module_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PopularTabTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='tab_title')),
                ('link', models.CharField(max_length=128, verbose_name='tab_link')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='links.populartab')),
            ],
            options={
                'verbose_name': 'popular_tab Translation',
                'db_table': 'links_populartab_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
