# Generated by Django 5.0.3 on 2024-05-17 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_module_populartab_alter_slider_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='type',
            field=models.CharField(choices=[('BRND', 'brand'), ('CTGR', 'category')], default='BRND', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='type_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='populartab',
            name='type',
            field=models.CharField(choices=[('BRND', 'brand'), ('CTGR', 'category')], default='BRND', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='populartab',
            name='type_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slider',
            name='type',
            field=models.CharField(choices=[('BRND', 'brand'), ('CTGR', 'category'), ('PROD', 'product')], default='BRND', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slider',
            name='type_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
