# Generated by Django 5.0.3 on 2024-05-10 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_producttypetranslation_name'),
        ('users', '0004_alter_favoriteproduct_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='favorite_brands',
        ),
        migrations.CreateModel(
            name='FavoriteBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.brand')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
