# Generated by Django 5.0.3 on 2024-05-10 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_producttypetranslation_name'),
        ('users', '0005_remove_profile_favorite_brands_favoritebrand'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite_brands',
            field=models.ManyToManyField(through='users.FavoriteBrand', to='products.brand'),
        ),
    ]
