# Generated by Django 5.0.3 on 2024-05-11 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_producttypetranslation_name'),
        ('users', '0006_profile_favorite_brands'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favoritebrand',
            unique_together={('brand', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='favoriteproduct',
            unique_together={('product', 'user')},
        ),
    ]
