# Generated by Django 5.0.3 on 2024-05-15 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cart_user'),
        ('products', '0013_alter_producttypetranslation_name'),
        ('users', '0008_remove_profile_favorite_brands_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cart',
            field=models.ManyToManyField(through='cart.Cart', to='products.product'),
        ),
        migrations.AlterField(
            model_name='user',
            name='favorite_products',
            field=models.ManyToManyField(related_name='favorite_by_users', through='users.FavoriteProduct', to='products.product'),
        ),
    ]
